/**
 * SkillNexus Advanced Data Seeder
 * Populates 200+ skills, industry trends, and curated learning resources.
 */

export const SKILLS_DATA = [
  // --- FRONTEND (20) ---
  { name: "React", category: "Frontend", description: "UI Component library", tags: ["web", "ui", "js"], industryWeight: 0.98, trendScore: 0.95 },
  { name: "Vue.js", category: "Frontend", description: "Progressive framework", tags: ["web", "ui"], industryWeight: 0.75, trendScore: 0.7 },
  { name: "Angular", category: "Frontend", description: "Enterprise platform", tags: ["web", "google"], industryWeight: 0.82, trendScore: 0.65 },
  { name: "Next.js", category: "Frontend", description: "React Framework", tags: ["ssr", "ssg"], industryWeight: 0.9, trendScore: 0.98 },
  { name: "TypeScript", category: "Frontend", description: "Typed JavaScript", tags: ["core", "safety"], industryWeight: 0.95, trendScore: 0.96 },
  { name: "Tailwind CSS", category: "Frontend", description: "Utility CSS", tags: ["styling"], industryWeight: 0.88, trendScore: 0.94 },
  { name: "Svelte", category: "Frontend", description: "Compiler-based UI", tags: ["perf"], industryWeight: 0.45, trendScore: 0.85 },
  { name: "Micro-frontends", category: "Frontend", description: "Architecture", tags: ["scaling"], industryWeight: 0.6, trendScore: 0.75 },
  { name: "WebAssembly", category: "Frontend", description: "Binary format", tags: ["performance"], industryWeight: 0.3, trendScore: 0.8 },
  { name: "Redux", category: "Frontend", description: "State management", tags: ["data"], industryWeight: 0.85, trendScore: 0.6 },
  { name: "Zustand", category: "Frontend", description: "Minimal state", tags: ["data"], industryWeight: 0.5, trendScore: 0.9 },
  { name: "Storybook", category: "Frontend", description: "Component dev", tags: ["testing"], industryWeight: 0.7, trendScore: 0.8 },
  { name: "Playwright", category: "Frontend", description: "E2E Testing", tags: ["qa"], industryWeight: 0.65, trendScore: 0.92 },
  { name: "Three.js", category: "Frontend", description: "3D Graphics", tags: ["creative", "webgl"], industryWeight: 0.4, trendScore: 0.78 },
  { name: "Vite", category: "Frontend", description: "Build tool", tags: ["DX"], industryWeight: 0.8, trendScore: 0.97 },
  { name: "PWA", category: "Frontend", description: "Progressive Apps", tags: ["mobile-web"], industryWeight: 0.55, trendScore: 0.65 },
  { name: "Accessibility (A11y)", category: "Frontend", description: "Inclusive web", tags: ["standards"], industryWeight: 0.9, trendScore: 0.85 },
  { name: "GraphQL (Client)", category: "Frontend", description: "API Querying", tags: ["data"], industryWeight: 0.7, trendScore: 0.75 },
  { name: "Module Federation", category: "Frontend", description: "Code sharing", tags: ["architecture"], industryWeight: 0.5, trendScore: 0.82 },
  { name: "CSS Grid", category: "Frontend", description: "Layout system", tags: ["design"], industryWeight: 0.9, trendScore: 0.7 },

  // --- BACKEND (20) ---
  { name: "Node.js", category: "Backend", description: "JS Runtime", tags: ["v8", "server"], industryWeight: 0.94, trendScore: 0.9 },
  { name: "Python", category: "Backend", description: "Versatile language", tags: ["ai", "scripts"], industryWeight: 0.97, trendScore: 0.98 },
  { name: "Go", category: "Backend", description: "Concurrent systems", tags: ["google", "fast"], industryWeight: 0.85, trendScore: 0.92 },
  { name: "Rust", category: "Backend", description: "Memory safety", tags: ["performance"], industryWeight: 0.5, trendScore: 0.99 },
  { name: "PostgreSQL", category: "Backend", description: "Relational DB", tags: ["sql", "data"], industryWeight: 0.92, trendScore: 0.94 },
  { name: "MongoDB", category: "Backend", description: "NoSQL document", tags: ["json"], industryWeight: 0.88, trendScore: 0.75 },
  { name: "Redis", category: "Backend", description: "In-memory cache", tags: ["performance"], industryWeight: 0.85, trendScore: 0.88 },
  { name: "NestJS", category: "Backend", description: "Node framework", tags: ["typescript", "modular"], industryWeight: 0.75, trendScore: 0.9 },
  { name: "FastAPI", category: "Backend", description: "Python API", tags: ["async", "speed"], industryWeight: 0.7, trendScore: 0.95 },
  { name: "Apache Kafka", category: "Backend", description: "Event streaming", tags: ["bigdata"], industryWeight: 0.8, trendScore: 0.85 },
  { name: "gRPC", category: "Backend", description: "High-perf RPC", tags: ["communication"], industryWeight: 0.65, trendScore: 0.82 },
  { name: "Serverless (AWS Lambda)", category: "Backend", description: "FaaS", tags: ["cloud"], industryWeight: 0.82, trendScore: 0.9 },
  { name: "Docker (Backend)", category: "Backend", description: "Isolation", tags: ["devops"], industryWeight: 0.9, trendScore: 0.92 },
  { name: "Prisma", category: "Backend", description: "ORM", tags: ["database", "ts"], industryWeight: 0.68, trendScore: 0.94 },
  { name: "Elixir", category: "Backend", description: "OTP / Beam", tags: ["fault-tolerant"], industryWeight: 0.35, trendScore: 0.72 },
  { name: "Java (Spring Boot)", category: "Backend", description: "Enterprise Java", tags: ["legacy", "stable"], industryWeight: 0.88, trendScore: 0.6 },
  { name: "Kubernetes (Backend perspective)", category: "Backend", description: "Orchestration", tags: ["scaling"], industryWeight: 0.8, trendScore: 0.85 },
  { name: "Elasticsearch", category: "Backend", description: "Search engine", tags: ["analytics"], industryWeight: 0.78, trendScore: 0.75 },
  { name: "Websockets", category: "Backend", description: "Real-time", tags: ["bi-directional"], industryWeight: 0.85, trendScore: 0.8 },
  { name: "RabbitMQ", category: "Backend", description: "Message broker", tags: ["pubsub"], industryWeight: 0.75, trendScore: 0.7 },

  // --- DATA SCIENCE (20) ---
  { name: "R Language", category: "Data Science", description: "Statistical computing", tags: ["stats"], industryWeight: 0.6, trendScore: 0.5 },
  { name: "Pandas", category: "Data Science", description: "Data manipulation", tags: ["python"], industryWeight: 0.95, trendScore: 0.9 },
  { name: "Scikit-Learn", category: "Data Science", description: "Classic ML", tags: ["python"], industryWeight: 0.92, trendScore: 0.85 },
  { name: "Matplotlib", category: "Data Science", description: "Visualizations", tags: ["charts"], industryWeight: 0.88, trendScore: 0.7 },
  { name: "Seaborn", category: "Data Science", description: "Statistical plots", tags: ["viz"], industryWeight: 0.8, trendScore: 0.75 },
  { name: "Tableau", category: "Data Science", description: "BI tool", tags: ["enterprise"], industryWeight: 0.85, trendScore: 0.8 },
  { name: "Power BI", category: "Data Science", description: "Microsoft BI", tags: ["enterprise"], industryWeight: 0.86, trendScore: 0.85 },
  { name: "BigQuery", category: "Data Science", description: "Data warehouse", tags: ["google", "sql"], industryWeight: 0.8, trendScore: 0.92 },
  { name: "Snowflake", category: "Data Science", description: "Cloud data repo", tags: ["saas"], industryWeight: 0.75, trendScore: 0.9 },
  { name: "PySpark", category: "Data Science", description: "Big data logic", tags: ["spark"], industryWeight: 0.82, trendScore: 0.88 },
  { name: "SQL (Data Analysis)", category: "Data Science", description: "Querying", tags: ["core"], industryWeight: 0.98, trendScore: 0.9 },
  { name: "Data Engineering", category: "Data Science", description: "Pipelines", tags: ["infrastructure"], industryWeight: 0.9, trendScore: 0.95 },
  { name: "ETL Processes", category: "Data Science", description: "Data movement", tags: ["enterprise"], industryWeight: 0.85, trendScore: 0.78 },
  { name: "Jupyter Notebooks", category: "Data Science", description: "Iterative dev", tags: ["viz"], industryWeight: 0.95, trendScore: 0.85 },
  { name: "TensorFlow (DS)", category: "Data Science", description: "Modeling", tags: ["deep-learning"], industryWeight: 0.8, trendScore: 0.75 },
  { name: "Data Cleaning", category: "Data Science", description: "Pre-processing", tags: ["core"], industryWeight: 0.98, trendScore: 0.9 },
  { name: "Feature Engineering", category: "Data Science", description: "Improving ML", tags: ["optimization"], industryWeight: 0.9, trendScore: 0.88 },
  { name: "A/B Testing", category: "Data Science", description: "Exp design", tags: ["product"], industryWeight: 0.85, trendScore: 0.8 },
  { name: "Time Series Analysis", category: "Data Science", description: "Forecasting", tags: ["stats"], industryWeight: 0.78, trendScore: 0.82 },
  { name: "NLP (Data Science)", category: "Data Science", description: "Text analysis", tags: ["language"], industryWeight: 0.8, trendScore: 0.92 },

  // --- AI / ML (20) ---
  { name: "Deep Learning", category: "AI / Machine Learning", description: "Neural networks", tags: ["ai"], industryWeight: 0.92, trendScore: 0.98 },
  { name: "Computer Vision", category: "AI / Machine Learning", description: "Visual processing", tags: ["images"], industryWeight: 0.85, trendScore: 0.9 },
  { name: "Generative AI", category: "AI / Machine Learning", description: "LLMs / Diffusion", tags: ["emerging"], industryWeight: 0.8, trendScore: 0.99 },
  { name: "PyTorch", category: "AI / Machine Learning", description: "ML research", tags: ["fb", "ai"], industryWeight: 0.9, trendScore: 0.98 },
  { name: "Keras", category: "AI / Machine Learning", description: "High-level ML", tags: ["abstraction"], industryWeight: 0.82, trendScore: 0.75 },
  { name: "Natural Language Processing", category: "AI / Machine Learning", description: "Language AI", tags: ["gpt"], industryWeight: 1.0, trendScore: 1.0 },
  { name: "Reinforcement Learning", category: "AI / Machine Learning", description: "Goal-based agents", tags: ["policy"], industryWeight: 0.65, trendScore: 0.8 },
  { name: "Hugging Face", category: "AI / Machine Learning", description: "Model hub", tags: ["transformers"], industryWeight: 0.75, trendScore: 0.98 },
  { name: "Fine-tuning", category: "AI / Machine Learning", description: "Adapting models", tags: ["customization"], industryWeight: 0.8, trendScore: 0.97 },
  { name: "Prompt Engineering", category: "AI / Machine Learning", description: "LLM optimization", tags: ["skill"], industryWeight: 0.5, trendScore: 0.99 },
  { name: "Vector Databases", category: "AI / Machine Learning", description: "Pinecone / Chroma", tags: ["rag"], industryWeight: 0.7, trendScore: 0.96 },
  { name: "RAG (Retrieval Augmentation)", category: "AI / Machine Learning", description: "Contextual AI", tags: ["knowledge"], industryWeight: 0.75, trendScore: 0.98 },
  { name: "Model Deployment", category: "AI / Machine Learning", description: "Serving models", tags: ["ops"], industryWeight: 0.88, trendScore: 0.92 },
  { name: "Explainable AI (XAI)", category: "AI / Machine Learning", description: "Transparent models", tags: ["ethics"], industryWeight: 0.6, trendScore: 0.85 },
  { name: "AI Ethics", category: "AI / Machine Learning", description: "Safety / Bias", tags: ["regulation"], industryWeight: 0.7, trendScore: 0.9 },
  { name: "GNN (Graph Neural Nets)", category: "AI / Machine Learning", description: "Network modeling", tags: ["advanced"], industryWeight: 0.45, trendScore: 0.78 },
  { name: "AutoML", category: "AI / Machine Learning", description: "Automated ML", tags: ["low-code"], industryWeight: 0.65, trendScore: 0.82 },
  { name: "On-device AI", category: "AI / Machine Learning", description: "Edge ML", tags: ["mobile"], industryWeight: 0.55, trendScore: 0.88 },
  { name: "Diffusion Models", category: "AI / Machine Learning", description: "Image generation", tags: ["creative"], industryWeight: 0.6, trendScore: 0.92 },
  { name: "Multi-modal AI", category: "AI / Machine Learning", description: "Combined vision/text", tags: ["vision"], industryWeight: 0.65, trendScore: 0.96 },

  // --- DEVOPS (20) ---
  { name: "Docker", category: "DevOps", description: "Containerization", tags: ["core"], industryWeight: 0.98, trendScore: 0.9 },
  { name: "Kubernetes", category: "DevOps", description: "Orchestration", tags: ["k8s", "scale"], industryWeight: 0.95, trendScore: 0.96 },
  { name: "CI/CD Pipelines", category: "DevOps", description: "Automation", tags: ["git"], industryWeight: 0.98, trendScore: 0.88 },
  { name: "Terraform", category: "DevOps", description: "IaC", tags: ["hashicorp"], industryWeight: 0.9, trendScore: 0.94 },
  { name: "Ansible", category: "DevOps", description: "Config management", tags: ["automation"], industryWeight: 0.8, trendScore: 0.65 },
  { name: "Prometheus", category: "DevOps", description: "Monitoring", tags: ["metrics"], industryWeight: 0.85, trendScore: 0.88 },
  { name: "Grafana", category: "DevOps", description: "Dashboards", tags: ["viz"], industryWeight: 0.86, trendScore: 0.9 },
  { name: "GitHub Actions", category: "DevOps", description: "Workflow automation", tags: ["ci"], industryWeight: 0.9, trendScore: 0.98 },
  { name: "Jenkins", category: "DevOps", description: "Classic CI", tags: ["automation"], industryWeight: 0.75, trendScore: 0.5 },
  { name: "ArgoCD", category: "DevOps", description: "GitOps", tags: ["k8s"], industryWeight: 0.6, trendScore: 0.92 },
  { name: "Istio", category: "DevOps", description: "Service mesh", tags: ["networking"], industryWeight: 0.55, trendScore: 0.8 },
  { name: "Helm", category: "DevOps", description: "K8s package manager", tags: ["config"], industryWeight: 0.8, trendScore: 0.85 },
  { name: "SRE (Site Reliability)", category: "DevOps", description: "Operations", tags: ["resilience"], industryWeight: 0.9, trendScore: 0.92 },
  { name: "Logging (ELK / Splunk)", category: "DevOps", description: "Observability", tags: ["data"], industryWeight: 0.88, trendScore: 0.8 },
  { name: "Linux Bash", category: "DevOps", description: "Scripting", tags: ["os", "core"], industryWeight: 0.98, trendScore: 0.75 },
  { name: "CloudFormation", category: "DevOps", description: "AWS IaC", tags: ["aws"], industryWeight: 0.7, trendScore: 0.65 },
  { name: "Security (DevSecOps)", category: "DevOps", description: "Safe pipelines", tags: ["sec"], industryWeight: 0.92, trendScore: 0.98 },
  { name: "Networking (TCP/IP)", category: "DevOps", description: "Foundations", tags: ["core"], industryWeight: 0.95, trendScore: 0.7 },
  { name: "Chaos Engineering", category: "DevOps", description: "Test resilience", tags: ["advanced"], industryWeight: 0.4, trendScore: 0.82 },
  { name: "FinOps", category: "DevOps", description: "Cloud cost optimization", tags: ["finance"], industryWeight: 0.75, trendScore: 0.95 },

  // --- CLOUD COMPUTING (20) ---
  { name: "AWS", category: "Cloud Computing", description: "Market leader", tags: ["amazon"], industryWeight: 1.0, trendScore: 0.9 },
  { name: "Azure", category: "Cloud Computing", description: "Microsoft Cloud", tags: ["microsoft"], industryWeight: 0.92, trendScore: 0.92 },
  { name: "Google Cloud (GCP)", category: "Cloud Computing", description: "Google's platform", tags: ["high-perf"], industryWeight: 0.85, trendScore: 0.88 },
  { name: "Cloud Migration", category: "Cloud Computing", description: "Moving to cloud", tags: ["enterprise"], industryWeight: 0.9, trendScore: 0.8 },
  { name: "Hybrid Cloud", category: "Cloud Computing", description: "Mixed environments", tags: ["scaling"], industryWeight: 0.82, trendScore: 0.85 },
  { name: "Serverless Architecture", category: "Cloud Computing", description: "Fully managed", tags: ["modern"], industryWeight: 0.88, trendScore: 0.94 },
  { name: "VPC Networking", category: "Cloud Computing", description: "Virtual private clouds", tags: ["segregation"], industryWeight: 0.9, trendScore: 0.75 },
  { name: "IAM (Identity Access)", category: "Cloud Computing", description: "Security", tags: ["core"], industryWeight: 0.98, trendScore: 0.85 },
  { name: "Object Storage (S3)", category: "Cloud Computing", description: "Blob storage", tags: ["data"], industryWeight: 0.98, trendScore: 0.8 },
  { name: "Cloud Databases (Aurora)", category: "Cloud Computing", description: "Managed DBs", tags: ["rds"], industryWeight: 0.9, trendScore: 0.88 },
  { name: "Edge Computing", category: "Cloud Computing", description: "Local processing", tags: ["speed"], industryWeight: 0.65, trendScore: 0.95 },
  { name: "CDN (CloudFront)", category: "Cloud Computing", description: "Global caching", tags: ["distribution"], industryWeight: 0.85, trendScore: 0.7 },
  { name: "DR (Disaster Recovery)", category: "Cloud Computing", description: "Backup strategy", tags: ["business-continuity"], industryWeight: 0.88, trendScore: 0.78 },
  { name: "Big Data (Cloud)", category: "Cloud Computing", description: "Redshift / BigQuery", tags: ["analytics"], industryWeight: 0.85, trendScore: 0.9 },
  { name: "Cloud Compliance", category: "Cloud Computing", description: "GDPR / HIPAA", tags: ["audit"], industryWeight: 0.82, trendScore: 0.85 },
  { name: "Multi-cloud Strategy", category: "Cloud Computing", description: "No vendor lock-in", tags: ["risk"], industryWeight: 0.6, trendScore: 0.92 },
  { name: "VDI (Virtual Desktop)", category: "Cloud Computing", description: "Remote work tech", tags: ["modern-desktop"], industryWeight: 0.5, trendScore: 0.6 },
  { name: "Cloud Governance", category: "Cloud Computing", description: "Policies", tags: ["management"], industryWeight: 0.75, trendScore: 0.82 },
  { name: "Kubernetes (Cloud Managed)", category: "Cloud Computing", description: "EKS / GKE", tags: ["k8s"], industryWeight: 0.9, trendScore: 0.92 },
  { name: "Cost Management", category: "Cloud Computing", description: "Billing logic", tags: ["finops"], industryWeight: 0.8, trendScore: 0.95 },

  // --- CYBERSECURITY (20) ---
  { name: "Ethical Hacking", category: "Cybersecurity", description: "Penetration testing", tags: ["offensive"], industryWeight: 0.92, trendScore: 0.9 },
  { name: "Cryptography", category: "Cybersecurity", description: "Encryption", tags: ["math", "data-sec"], industryWeight: 0.95, trendScore: 0.75 },
  { name: "Zero Trust Network", category: "Cybersecurity", description: "Never trust logic", tags: ["modern"], industryWeight: 0.82, trendScore: 0.98 },
  { name: "Network Security", category: "Cybersecurity", description: "Firewalls / IDS", tags: ["core"], industryWeight: 0.98, trendScore: 0.8 },
  { name: "Cloud Security", category: "Cybersecurity", description: "Secure cloud", tags: ["aws-sec"], industryWeight: 0.9, trendScore: 0.98 },
  { name: "Identity Security", category: "Cybersecurity", description: "Auth / MFA", tags: ["access"], industryWeight: 0.98, trendScore: 0.92 },
  { name: "Incident Response", category: "Cybersecurity", description: "Hacking mitigation", tags: ["defense"], industryWeight: 0.9, trendScore: 0.85 },
  { name: "SIEM Systems", category: "Cybersecurity", description: "Log monitoring", tags: ["analytics"], industryWeight: 0.8, trendScore: 0.82 },
  { name: "App Security (SAST/DAST)", category: "Cybersecurity", description: "Vulnerability analysis", tags: ["dev"], industryWeight: 0.88, trendScore: 0.95 },
  { name: "SOC (Security Ops)", category: "Cybersecurity", description: "Monitoring teams", tags: ["ops"], industryWeight: 0.85, trendScore: 0.8 },
  { name: "Compliance (HIPAA/ISO)", category: "Cybersecurity", description: "Auditing", tags: ["legal"], industryWeight: 0.82, trendScore: 0.8 },
  { name: "Malware Analysis", category: "Cybersecurity", description: "Reverse engineering", tags: ["forensics"], industryWeight: 0.65, trendScore: 0.75 },
  { name: "DDoS Mitigation", category: "Cybersecurity", description: "Flood control", tags: ["cloudflare"], industryWeight: 0.8, trendScore: 0.7 },
  { name: "Phishing Protection", category: "Cybersecurity", description: "Human social eng", tags: ["training"], industryWeight: 0.95, trendScore: 0.85 },
  { name: "Ransomware Prevention", category: "Cybersecurity", description: "Data protection", tags: ["risk"], industryWeight: 0.9, trendScore: 0.98 },
  { name: "Database Security", category: "Cybersecurity", description: "Locked records", tags: ["sql"], industryWeight: 0.9, trendScore: 0.75 },
  { name: "IoT Security", category: "Cybersecurity", description: "Device safety", tags: ["hardware"], industryWeight: 0.5, trendScore: 0.88 },
  { name: "Blockchain Security", category: "Cybersecurity", description: "Smart contract audit", tags: ["web3"], industryWeight: 0.35, trendScore: 0.7 },
  { name: "Endpoint Security", category: "Cybersecurity", description: "Device protection", tags: ["edr"], industryWeight: 0.85, trendScore: 0.88 },
  { name: "Forensics", category: "Cybersecurity", description: "Digital investigation", tags: ["law"], industryWeight: 0.6, trendScore: 0.7 },

  // --- MOBILE DEVELOPMENT (20) ---
  { name: "Swift", category: "Mobile Development", description: "iOS Native", tags: ["apple"], industryWeight: 0.9, trendScore: 0.7 },
  { name: "Kotlin", category: "Mobile Development", description: "Android Native", tags: ["google"], industryWeight: 0.9, trendScore: 0.75 },
  { name: "React Native", category: "Mobile Development", description: "Cross-platform", tags: ["fb", "js"], industryWeight: 0.95, trendScore: 0.85 },
  { name: "Flutter", category: "Mobile Development", description: "UI toolkit", tags: ["dart", "google"], industryWeight: 0.85, trendScore: 0.9 },
  { name: "Jetpack Compose", category: "Mobile Development", description: "Native Android UI", tags: ["modern"], industryWeight: 0.75, trendScore: 0.92 },
  { name: "SwiftUI", category: "Mobile Development", description: "Native iOS UI", tags: ["modern"], industryWeight: 0.75, trendScore: 0.92 },
  { name: "Mobile UI Design", category: "Mobile Development", description: "UX focus", tags: ["design"], industryWeight: 0.9, trendScore: 0.8 },
  { name: "Offline Data (SQLite)", category: "Mobile Development", description: "Local storage", tags: ["database"], industryWeight: 0.98, trendScore: 0.6 },
  { name: "Firebase (Mobile)", category: "Mobile Development", description: "BaaS", tags: ["realtime"], industryWeight: 0.95, trendScore: 0.85 },
  { name: "Mobile Security", category: "Mobile Development", description: "Auth / Bio", tags: ["sec"], industryWeight: 0.9, trendScore: 0.88 },
  { name: "App Store Optimization", category: "Mobile Development", description: "ASO", tags: ["marketing"], industryWeight: 0.7, trendScore: 0.75 },
  { name: "Push Notifications", category: "Mobile Development", description: "Retention", tags: ["fcm", "apns"], industryWeight: 0.95, trendScore: 0.7 },
  { name: "Deep Linking", category: "Mobile Development", description: "Navigation", tags: ["routing"], industryWeight: 0.85, trendScore: 0.65 },
  { name: "Mobile Testing (Appium)", category: "Mobile Development", description: "QA automation", tags: ["testing"], industryWeight: 0.7, trendScore: 0.8 },
  { name: "CI/CD (Fastlane)", category: "Mobile Development", description: "Build pipelines", tags: ["devops"], industryWeight: 0.75, trendScore: 0.82 },
  { name: "GraphQL (Mobile)", category: "Mobile Development", description: "Querying", tags: ["apollo"], industryWeight: 0.65, trendScore: 0.78 },
  { name: "Augmented Reality (ARKit)", category: "Mobile Development", description: "Spatial", tags: ["immersive"], industryWeight: 0.3, trendScore: 0.85 },
  { name: "In-app Payments", category: "Mobile Development", description: "StoreKit / Billing", tags: ["finance"], industryWeight: 0.9, trendScore: 0.75 },
  { name: "Wearables (WatchOS)", category: "Mobile Development", description: "Local device", tags: ["iot"], industryWeight: 0.4, trendScore: 0.65 },
  { name: "Core ML (Mobile)", category: "Mobile Development", description: "On-device AI", tags: ["ai"], industryWeight: 0.55, trendScore: 0.92 },

  // --- UI/UX DESIGN (20) ---
  { name: "Figma", category: "UI/UX Design", description: "Collaborative design", tags: ["tools"], industryWeight: 1.0, trendScore: 0.95 },
  { name: "Wireframing", category: "UI/UX Design", description: "Structural blueprints", tags: ["process"], industryWeight: 0.95, trendScore: 0.6 },
  { name: "Prototyping", category: "UI/UX Design", description: "Interactive mockups", tags: ["interaction"], industryWeight: 0.92, trendScore: 0.85 },
  { name: "User Research", category: "UI/UX Design", description: "Insight gathering", tags: ["psychology"], industryWeight: 0.9, trendScore: 0.92 },
  { name: "Design Systems", category: "UI/UX Design", description: "Scalable UI", tags: ["systemic"], industryWeight: 0.88, trendScore: 0.98 },
  { name: "Visual Design", category: "UI/UX Design", description: "Aesthetics", tags: ["art"], industryWeight: 0.95, trendScore: 0.7 },
  { name: "Typography", category: "UI/UX Design", description: "Text layout", tags: ["foundations"], industryWeight: 0.9, trendScore: 0.65 },
  { name: "Color Theory", category: "UI/UX Design", description: "Mood / Palette", tags: ["design"], industryWeight: 0.9, trendScore: 0.6 },
  { name: "Auto Layout", category: "UI/UX Design", description: "Responsive Figma", tags: ["efficiency"], industryWeight: 0.95, trendScore: 0.9 },
  { name: "User Journey Mapping", category: "UI/UX Design", description: "Experience path", tags: ["strategy"], industryWeight: 0.85, trendScore: 0.82 },
  { name: "Information Architecture", category: "UI/UX Design", description: "Org hierarchy", tags: ["ux"], industryWeight: 0.82, trendScore: 0.75 },
  { name: "Interaction Design", category: "UI/UX Design", description: "Motion / State", tags: ["engaging"], industryWeight: 0.8, trendScore: 0.88 },
  { name: "Usability Testing", category: "UI/UX Design", description: "Validation", tags: ["qa"], industryWeight: 0.9, trendScore: 0.9 },
  { name: "Design Handoff", category: "UI/UX Design", description: "Specs for dev", tags: ["collab"], industryWeight: 0.95, trendScore: 0.85 },
  { name: "Mobile-First Design", category: "UI/UX Design", description: "Priority setup", tags: ["standards"], industryWeight: 0.98, trendScore: 0.7 },
  { name: "Accessibility (Design)", category: "UI/UX Design", description: "Inclusive UI", tags: ["wcag"], industryWeight: 0.95, trendScore: 0.96 },
  { name: "Branding", category: "UI/UX Design", description: "Identity", tags: ["mkt"], industryWeight: 0.8, trendScore: 0.6 },
  { name: "Motion Graphic", category: "UI/UX Design", description: "Animation", tags: ["engagement"], industryWeight: 0.6, trendScore: 0.92 },
  { name: "Adobe Creative Suite", category: "UI/UX Design", description: "Classic tools", tags: ["ps", "ai"], industryWeight: 0.7, trendScore: 0.4 },
  { name: "UX Copywriting", category: "UI/UX Design", description: "Micro-content", tags: ["voice"], industryWeight: 0.75, trendScore: 0.85 }
];

export const INDUSTRY_DEMAND_HISTORICAL = [
  // Generative AI
  { skill: "Generative AI", year: 2024, demandScore: 40, growthRate: 300 },
  { skill: "Generative AI", year: 2025, demandScore: 85, growthRate: 110 },
  { skill: "Generative AI", year: 2026, demandScore: 98, growthRate: 15 },
  // React
  { skill: "React", year: 2024, demandScore: 92, growthRate: 5 },
  { skill: "React", year: 2025, demandScore: 94, growthRate: 2 },
  { skill: "React", year: 2026, demandScore: 95, growthRate: 1 },
  // Rust
  { skill: "Rust", year: 2024, demandScore: 30, growthRate: 50 },
  { skill: "Rust", year: 2025, demandScore: 55, growthRate: 83 },
  { skill: "Rust", year: 2026, demandScore: 78, growthRate: 42 },
  // Cybersecurity
  { skill: "Cloud Security", year: 2024, demandScore: 70, growthRate: 20 },
  { skill: "Cloud Security", year: 2025, demandScore: 88, growthRate: 25 },
  { skill: "Cloud Security", year: 2026, demandScore: 96, growthRate: 9 }
];

export const CURATED_RESOURCES = [
  // --- USER PROVIDED YOUTUBE MASTER CLASSES ---
  { 
    title: "MERN Stack Full Course 2026", 
    type: "Video", 
    platform: "YouTube", 
    skillsCovered: ["React", "Node.js", "MongoDB", "Express.js", "JavaScript"], 
    difficulty: "Beginner", 
    duration: "40h", 
    rating: 4.9, 
    domain: "Full Stack",
    url: "https://www.youtube.com/playlist?list=PLDzeHZWIZsTo0wSBcg4-NMIbC0L8evLrD" 
  },
  { 
    title: "AI & Machine Learning Foundations", 
    type: "Video", 
    platform: "YouTube", 
    skillsCovered: ["Generative AI", "AI Ethics", "Python", "Deep Learning"], 
    difficulty: "Beginner", 
    duration: "12h", 
    rating: 4.8, 
    domain: "AI / Machine Learning",
    url: "https://www.youtube.com/watch?v=D1eL1EnxXXQ" 
  },
  { 
    title: "Machine Learning Engineering Masterclass", 
    type: "Video", 
    platform: "YouTube", 
    skillsCovered: ["Machine Learning", "Scikit-Learn", "Python", "Data Cleaning"], 
    difficulty: "Intermediate", 
    duration: "30h", 
    rating: 4.9, 
    domain: "AI / Machine Learning",
    url: "https://www.youtube.com/watch?v=ukzFI9rgwfU&list=PLEiEAq2VkUULYYgj13YHUWmRePqiu8Ddy" 
  },
  { 
    title: "Data Science Specialization (Complete)", 
    type: "Video", 
    platform: "YouTube", 
    skillsCovered: ["Data Science", "Pandas", "SQL", "Matplotlib"], 
    difficulty: "Beginner", 
    duration: "25h", 
    rating: 4.7, 
    domain: "Data Science",
    url: "https://www.youtube.com/watch?v=gDZ6czwuQ18" 
  },
  { 
    title: "DevOps Engineering Bootcamp (Part 1)", 
    type: "Video", 
    platform: "YouTube", 
    skillsCovered: ["Docker", "Kubernetes", "CI/CD Pipelines", "Terraform", "DevOps"], 
    difficulty: "Intermediate", 
    duration: "20h", 
    rating: 4.8, 
    domain: "DevOps",
    url: "https://www.youtube.com/watch?v=SOTamWNgDKc&list=PLWKjhJtqVAbkzvvpY12KkfiIGso9A_Ixs" 
  },
  { 
    title: "DevOps & Cloud Masterclass (Part 2)", 
    type: "Video", 
    platform: "YouTube", 
    skillsCovered: ["AWS", "Cloud Native", "GitOps", "ArgoCD"], 
    difficulty: "Advanced", 
    duration: "18h", 
    rating: 4.9, 
    domain: "DevOps",
    url: "https://www.youtube.com/watch?v=Ou9j73aWgyE&list=PLdpzxOOAlwvIc1TjTwopNSjRJkzES2ZXk" 
  },
  { 
    title: "AWS Cloud Practitioner Masterclass", 
    type: "Video", 
    platform: "YouTube", 
    skillsCovered: ["AWS", "Cloud Computing", "VPC Networking", "IAM"], 
    difficulty: "Beginner", 
    duration: "15h", 
    rating: 4.9, 
    domain: "Cloud Computing",
    url: "https://www.youtube.com/watch?v=2LaAJq1lB1Q&list=PL9ooVrP1hQOFtZ5oAAeOgi_nH-txMcDMu" 
  },
  { 
    title: "Cyber Security Certification Course", 
    type: "Video", 
    platform: "YouTube", 
    skillsCovered: ["Cybersecurity", "Network Security", "Ethical Hacking", "Cryptography"], 
    difficulty: "Beginner", 
    duration: "18h", 
    rating: 4.8, 
    domain: "Cybersecurity",
    url: "https://www.youtube.com/watch?v=lpa8uy4DyMo&list=PL9ooVrP1hQOGPQVeapGsJCktzIO4DtI4_" 
  },
  { 
    title: "Android & Kotlin Development 2025", 
    type: "Video", 
    platform: "YouTube", 
    skillsCovered: ["Mobile Development", "Kotlin", "Jetpack Compose", "SQLite"], 
    difficulty: "Intermediate", 
    duration: "32h", 
    rating: 4.7, 
    domain: "Mobile Development",
    url: "https://www.youtube.com/watch?v=blKkRoZPxLc" 
  },
  { 
    title: "UI/UX Design Masterclass (Figma Focused)", 
    type: "Video", 
    platform: "YouTube", 
    skillsCovered: ["UI/UX Design", "Figma", "Design Systems", "Prototyping"], 
    difficulty: "Beginner", 
    duration: "14h", 
    rating: 4.9, 
    domain: "UI/UX Design",
    url: "https://www.youtube.com/watch?v=O5IXf8qB9U4&list=PLdvOfoe7PXT0ouChAnR1nHlT8BJIo5hP_" 
  },
  {
    title: "Node.js & Express.js Full Course 2025",
    type: "Video",
    platform: "YouTube",
    skillsCovered: ["Node.js", "Express.js", "Backend", "REST APIs"],
    difficulty: "Beginner",
    duration: "10h",
    rating: 4.9,
    domain: "Backend",
    url: "https://www.youtube.com/watch?v=vfaRzV3P92o"
  },
  {
    title: "Docker Masterclass 2025",
    type: "Video",
    platform: "YouTube",
    skillsCovered: ["Docker", "DevOps", "Containers"],
    difficulty: "Intermediate",
    duration: "5h",
    rating: 4.8,
    domain: "DevOps",
    url: "https://www.youtube.com/watch?v=exmSJpJvIPs"
  },
  {
    title: "Python 2025: From Zero to Hero",
    type: "Video",
    platform: "YouTube",
    skillsCovered: ["Python", "Programming Basics", "Automation"],
    difficulty: "Beginner",
    duration: "12h",
    rating: 4.9,
    domain: "Backend",
    url: "https://www.youtube.com/watch?v=K5KVEU3aaeQ"
  },

  // --- ORIGINAL CURATED ---
  { title: "React Mastery 2026", type: "Course", platform: "Udemy", skillsCovered: ["React", "JavaScript", "Next.js"], difficulty: "Intermediate", duration: "25h", rating: 4.8, domain: "Frontend", url: "https://udemy.com" },
  { title: "LLM Fundamentals", type: "Video", platform: "YouTube", skillsCovered: ["Generative AI", "NLP", "Python"], difficulty: "Beginner", duration: "3h", rating: 4.9, domain: "AI / Machine Learning", url: "https://youtube.com" },
  { title: "Advanced Rust for Systems", type: "Course", platform: "Pluralsight", skillsCovered: ["Rust", "Backend"], difficulty: "Advanced", duration: "18h", rating: 4.7, domain: "Backend", url: "https://pluralsight.com" },
  { title: "Figma for Professional Design", type: "Video", platform: "Skillshare", skillsCovered: ["Figma", "UI/UX Design"], difficulty: "Intermediate", duration: "5h", rating: 4.6, domain: "UI/UX Design", url: "https://skillshare.com" },
  { title: "Cloud Security Handbook", type: "Article", platform: "AWS Blog", skillsCovered: ["Cloud Security", "AWS"], difficulty: "Advanced", duration: "1h", rating: 4.8, domain: "Cloud Computing", url: "https://aws.amazon.com/blog" },
  { title: "The Joy of Frontend", type: "Course", platform: "JoshComeau", skillsCovered: ["React", "CSS Grid", "Tailwind CSS"], difficulty: "Beginner", duration: "45h", rating: 5.0, domain: "Frontend", url: "https://joshwcomeau.com" },
  { title: "Go for Distributed Systems", type: "Course", platform: "Coursera", skillsCovered: ["Go", "Distributed Systems", "Backend"], difficulty: "Advanced", duration: "30h", rating: 4.8, domain: "Backend", url: "https://coursera.com" }
];
