import type { Resource } from '../types/database';

export const resources: Resource[] = [
  {
    id: '03dfb9bf-a596-40a8-855a-14169a84a6bc',
    title: 'UI/UX Design with Figma',
    description: 'Master interface and user experience design.',
    domain: 'UI/UX Design',
    url: 'https://coursera.org/professional-certificates/google-ux-design',
    type: 'Course',
    platform: 'Google',
    skillsCovered: ['Figma'],
    difficulty: 'Beginner',
    rating: 4.8,
    duration: '20 hours'
  },
  {
    id: '0c8fb483-7466-45fb-a4a1-6b6230458655',
    title: 'Microservices Architecture',
    description: 'Design and implement scalable microservices systems.',
    domain: 'Backend',
    url: 'https://pluralsight.com',
    type: 'Course',
    platform: 'Pluralsight',
    skillsCovered: ['Microservices'],
    difficulty: 'Advanced',
    rating: 4.7,
    duration: '12 hours'
  },
  {
    id: '0e2a8d-743b-49f7-8cea-cec2cf2706ff',
    title: 'React Fundamentals',
    description: 'Learn modern React development from scratch.',
    domain: 'Frontend',
    url: 'https://coursera.org/learn/react-fundamentals',
    type: 'Course',
    platform: 'Coursera',
    skillsCovered: ['React'],
    difficulty: 'Beginner',
    rating: 4.9,
    duration: '15 hours'
  },
  {
    id: '21a19542-8a36-4f8f-b546-720001883ab4',
    title: 'TensorFlow for Beginners',
    description: 'Start building AI models using TensorFlow.',
    domain: 'AI/Machine Learning',
    url: 'https://developers.google.com',
    type: 'Course',
    platform: 'Google',
    skillsCovered: ['TensorFlow'],
    difficulty: 'Intermediate',
    rating: 4.6,
    duration: '10 hours'
  },
  {
    id: '248d752c-8217-46ed-8dfc-5aca1b85e01d',
    title: 'CI/CD Pipeline Fundamentals',
    description: 'Automate testing and deployment workflows.',
    domain: 'DevOps',
    url: 'https://pluralsight.com',
    type: 'Course',
    platform: 'Pluralsight',
    skillsCovered: ['CI/CD'],
    difficulty: 'Intermediate',
    rating: 4.8,
    duration: '8 hours'
  },
  {
    id: '28052ac9-48ff-44c3-88c5-112ab47715cd',
    title: 'Machine Learning with Python',
    description: 'Introduction to machine learning algorithms using Python.',
    domain: 'AI/Machine Learning',
    url: 'https://coursera.org',
    type: 'Course',
    platform: 'Coursera',
    skillsCovered: ['Machine Learning'],
    difficulty: 'Beginner',
    rating: 4.7,
    duration: '22 hours'
  },
  {
    id: '31be914a-6e20-43c6-951d-78d039747ff8',
    title: 'Mobile UI Design Principles',
    description: 'Design intuitive and engaging mobile interfaces.',
    domain: 'Mobile Development',
    url: 'https://interaction-design.org',
    type: 'Course',
    platform: 'Interaction Design Foundation',
    skillsCovered: ['Mobile UI'],
    difficulty: 'Intermediate',
    rating: 4.6,
    duration: '12 hours'
  },
  {
    id: '33debf32-970c-4adc-b3ef-19b914a2a39d',
    title: 'Google Cloud Associate Engineer Prep',
    description: 'Prepare for Google Cloud certification.',
    domain: 'Cloud Computing',
    url: 'https://cloud.google.com',
    type: 'Course',
    platform: 'Google Cloud Skills Boost',
    skillsCovered: ['Google Cloud'],
    difficulty: 'Intermediate',
    rating: 4.8,
    duration: '15 hours'
  },
  {
    id: '3721c234-8bf1-40f9-b081-f8c945333cbc',
    title: 'Tailwind CSS Masterclass',
    description: 'Build modern, responsive interfaces quickly using Tailwind CSS.',
    domain: 'Frontend',
    url: 'https://youtube.com',
    type: 'Course',
    platform: 'YouTube',
    skillsCovered: ['Tailwind CSS'],
    difficulty: 'Intermediate',
    rating: 4.9,
    duration: '6 hours'
  },
  {
    id: '3ae0a0e8-00be-4d82-97fd-26b6b954f9e3',
    title: 'Build Full Stack Apps with Next.js',
    description: 'Create production-ready full stack applications using Next.js and modern tools.',
    domain: 'Full Stack',
    url: 'https://frontendmasters.com',
    type: 'Course',
    platform: 'Frontend Masters',
    skillsCovered: ['Next.js'],
    difficulty: 'Intermediate',
    rating: 4.9,
    duration: '18 hours'
  },
  {
    id: '3cc13ced-63ed-4208-850a-4b1ec5856ed2',
    title: 'Docker Essentials',
    description: 'Containerize applications using Docker.',
    domain: 'DevOps',
    url: 'https://kodekloud.com',
    type: 'Course',
    platform: 'KodeKloud',
    skillsCovered: ['Docker'],
    difficulty: 'Beginner',
    rating: 4.8,
    duration: '10 hours'
  },
  {
    id: '3d71034c-3dcf-4f99-9a9e-1a6a7fe27e32',
    title: 'PostgreSQL Database Design',
    description: 'Learn relational database design and optimization techniques.',
    domain: 'Backend',
    url: 'https://coursera.org',
    type: 'Course',
    platform: 'Coursera',
    skillsCovered: ['PostgreSQL'],
    difficulty: 'Intermediate',
    rating: 4.7,
    duration: '14 hours'
  },
  {
    id: '449c98d3-b28b-4c77-b518-16fcde587e97',
    title: 'React Fundamentals',
    description: 'Master React basics with hands-on projects and real-world examples.',
    domain: 'Frontend',
    url: 'https://coursera.org',
    type: 'Course',
    platform: 'Coursera',
    skillsCovered: ['React'],
    difficulty: 'Beginner',
    rating: 4.8,
    duration: '16 hours'
  },
  {
    id: '46945618-5e7c-4039-95d5-7d33656b6cfc',
    title: 'Python for Data Analysis',
    description: 'Analyze and manipulate data effectively using Python libraries.',
    domain: 'Data Science',
    url: 'https://datacamp.com',
    type: 'Course',
    platform: 'DataCamp',
    skillsCovered: ['Python'],
    difficulty: 'Beginner',
    rating: 4.7,
    duration: '9 hours'
  },
  {
    id: '54d8d5cd-2b1b-4802-b9f0-8cf7c778c4bd',
    title: 'Design Systems Essentials',
    description: 'Build scalable and consistent design systems.',
    domain: 'UI/UX Design',
    url: 'https://frontendmasters.com',
    type: 'Course',
    platform: 'Frontend Masters',
    skillsCovered: ['Design Systems'],
    difficulty: 'Advanced',
    rating: 4.9,
    duration: '11 hours'
  },
  {
    id: '598d6d68-3725-44a6-a44b-8fe0d5b6b63d',
    title: 'Node.js API Development',
    description: 'Build scalable REST APIs using Node.js and Express.',
    domain: 'Backend',
    url: 'https://udemy.com/course/nodejs-api-development',
    type: 'Course',
    platform: 'Udemy',
    skillsCovered: ['Node.js'],
    difficulty: 'Intermediate',
    rating: 4.8,
    duration: '13 hours'
  }

];

